name: Skylar Schipper
highlighter: true
markdown: redcarpet
post:
  template: post
editor: 'Writer\ Pro'
preview: 'Marked\ 2'
exclude: [Gemfile, Gemfile.lock, Rakefile, tasks]
include: [".well-known"]
