name: Skylar Schipper
highlighter: true
markdown: redcarpet
post:
  template: post
collections:
  - projects
editor: 'iA\ Writer\ Pro'
preview: 'Marked\ 2'
exclude: [Gemfile, Gemfile.lock, Rakefile, tasks]
include: [".well-known"]
description: "I'm a developer, maker, and enjoyer of fine thing.  These are my thoughts."
hostname: 'skylarsch.com'
